import { Project } from './types';

export const generateCSV = (project: Project) => {
  const rows: string[][] = [];

  // 1. Header Section
  rows.push(["COMPANY DETAILS"]);
  rows.push(["Renowix Renovations"]);
  rows.push(["C-32, Sector 51, Noida, UP 201301"]);
  rows.push(["Phone: +91 92114 29635 | Email: info@renowix.in"]);
  rows.push([]); // Spacer

  rows.push(["MEASUREMENT REPORT"]);
  rows.push([]); // Spacer

  // 2. Client Section (2 columns visual layout simulated)
  rows.push(["CLIENT DETAILS", "", "SITE DETAILS"]);
  rows.push([project.client.name, "", project.client.name]);
  rows.push([project.client.address.replace(/\n/g, ' '), "", project.client.address.replace(/\n/g, ' ')]);
  rows.push(["Date:", project.date]);
  rows.push([]); // Spacer

  // 3. Room-by-Room Structure
  project.services.forEach((service) => {
    // Service Header
    rows.push([`SERVICE CATEGORY: ${service.name.toUpperCase()}`]);
    rows.push([`Description: ${service.desc}`]);
    rows.push([]); // Spacer

    // Table Header for this service
    rows.push([
      "ROOM / ITEM NAME",
      "DESCRIPTION",
      "LENGTH",
      "WIDTH",
      "HEIGHT",
      "QUANTITY",
      "UNIT",
      "RATE",
      "AMOUNT",
      "REMARKS"
    ]);

    let serviceTotalArea = 0;
    let serviceTotalCost = 0;

    service.items.forEach((item) => {
      // Logic to format dimensions based on item type
      let lenStr = item.l ? item.l.toString() : "-";
      let widthStr = item.b ? item.b.toString() : "-";
      
      // If it's a painting job with walls, we might want to list walls in remarks or summary
      // For CSV simplicity, we output the aggregate net values, but allow remarks for details
      if (item.walls && item.walls.length > 0) {
        const wallDetails = item.walls.map(w => w.width).join('+');
        widthStr = `Walls: ${wallDetails}`;
      }
      
      const heightStr = item.height ? item.height.toString() : "-";
      const qtyStr = item.q ? item.q.toString() : item.netArea.toString();

      rows.push([
        item.name,
        service.name, // Description column
        lenStr,
        widthStr,
        heightStr,
        qtyStr,
        service.unit,
        item.rate.toFixed(2),
        item.cost.toFixed(2),
        item.remarks || ""
      ]);

      serviceTotalArea += item.netArea;
      serviceTotalCost += item.cost;
    });

    // Service Subtotal
    rows.push([
      "TOTAL FOR SECTION",
      "", "", "", "",
      serviceTotalArea.toFixed(2),
      service.unit,
      "",
      serviceTotalCost.toFixed(2),
      ""
    ]);
    rows.push([]); // Spacer
    rows.push([]); // Double spacer between services
  });

  // 4. Grand Total Summary
  const grandTotal = project.services.reduce((sum, s) => sum + s.items.reduce((is, i) => is + i.cost, 0), 0);
  
  rows.push(["SUMMARY"]);
  rows.push(["TOTAL ESTIMATED COST", "", "", "", "", "", "", "", grandTotal.toFixed(2)]);
  rows.push([]);
  rows.push(["Generated by Renowix Surveyor Pro"]);

  // Convert to CSV string
  const csvContent = rows
    .map(e => e.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(","))
    .join("\n");

  return csvContent;
};

export const downloadCSV = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement("a");
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute("download", filename);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
};